### ISSUE TITLE
gold-sysroot-lib64 patch missing for binutils 2.33.1 and 2.34

### ISSUE THREAD

**Issue by nehaljwani** [conda-forge/crosstool-ng-feedstock#12]
Please port the following patch from @mingwandroid to 2.33.1 and 2.34 otherwise gold linker cannot be used with CDT packages which have their libraries present in `$(gcc --print-sysroot)/{lib64,usr/lib64}`

https://github.com/conda-forge/crosstool-ng/blob/master/packages/binutils/2.31.1/510-add-lib64-to-sysroot-paths.patch

**Comment by isuruf** [comment]
Can you open this in https://github.com/conda-forge/binutils-feedstock/ ?

**Comment by isuruf** [comment]
@mingwandroid, @nehaljwani, do you know if this patch is sent upstream to `crosstool-ng`?

**Comment by nehaljwani** [comment]
I don't know if it has been sent upstream. Let's continue at https://github.com/conda-forge/binutils-feedstock/issues/26

**Comment by nehaljwani** [comment]
Actually, fix will be here, to I'll let you close this.

**Comment by isuruf** [comment]
`binutils-feedstock` does not use `crosstool-ng` conda package. See https://github.com/conda-forge/binutils-feedstock/blob/master/recipe/meta.yaml#L14-L18

**Comment by nehaljwani** [comment]
Ah, okay, closing this one then, let's continue there.
